### ISSUE TITLE
Should replays include the beginning of the turn, like handling morning abilities?

### ISSUE THREAD

**Issue by KingSupernova31** [KaiGeffen/Celestial#148]
When I press the replay button, morning animations don't appear in the replay; they only appear the first time I start the turn.

 The only exception is when I have a Moon, which still shows animations for the cards it's triggering even in the replay.

**Comment by KaiGeffen** [comment]
Yeah, morning animations happen during the start of round, so they won't show in a replay (Same as drawing card or passing/playing). They showed for you the first time because it was *Night Phaser* then *Morning Phase* then *Day Phase*.
As a part of rethinking the ux for replay, interpretability of these sorts of effects is important. But unclear exactly how that will look for the 0.7 release.

**Comment by KingSupernova31** [comment]
Ah, that makes sense. Never noticed the card draw thing, oops. And now that you point it out, it's obviously not replaying *everything* prior, since then it would include cards I've already played in the new turn.

I think what might have been leading me to think about it as a replay of "everything prior" rather than just "the resolution phase of last turn" is the fact that the sun/moon rotation animation happens in the replay. I think of that as "changing turns", not "part of resolution".

But yeah now that you explain it this isn't a bug. Editing to enhancement, but I'm not sure it's even necessary; the replay only including the resolution phase does make sense.

**Comment by KingSupernova31** [comment]
Wait no, what am I talking about. Moon showing the animations in the replay is still a bug under the correct interpretation. I'm just gonna close this and open a clean ticket.

**Comment by KingSupernova31** [comment]
Ok see #150 and #151. Sorry for my confusion on the subject.
